DROP TABLE IF EXISTS `artists`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `artists` (
  `artistName` varchar(100) NOT NULL,
  `artistDate` varchar(100) NOT NULL,
  `artistGenre` varchar(100) NOT NULL,
  `artistOrigin` varchar(100) NOT NULL,
  `artistLabels` varchar(100) NOT NULL,
  `bioText` text NOT NULL,
  PRIMARY KEY (`artistName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

/*
-- Query: SELECT * FROM themusicvault.artists
LIMIT 0, 1000

-- Date: 2017-12-06 13:42
*/
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Adele','2006-present','Soul, pop','London, England','Vocals','Adele Laurie Blue Adkins is an English singer and songwriter. After graduating from the BRIT school for performing Arts and Technology in 2006, Adele was given a recording contract by XL recordings after a friend posted her demo on Myspace the same year. In 2007, she received Brit Awards Critics choice award and won the BBC Sound of 2008 poll. Her debut album 19 was released in 2008 to commercial and critical success. If is certified seven times platinum in the UK, and three times platinum in the US.');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Blake Shelton','2001-present','Country','Nashville Tennessee','Giant','Blake Tollison Shelton (born June 18, 1976) is an American singer-songwriter and television personality. In 2001, he made his debut with the single \"Austin\". The lead-off single from his self-titled debut album, \"Austin\" spent five weeks at number one on the Billboard Hot Country Songs chart. The now Platinum-certified debut album also produced two more top 20 entries (\"All Over Me\" and \"Ol\' Red\").Although the album was released on Giant Records Nashville, he was transferred to Warner Bros. Records Nashville after Giant closed in late 2001.');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Bon Jovi','1983-present','Hard rock','Sayreville, New Jersey, U.S.','Island','Bon Jovi is an American rock band from Sayreville, New Jersey. Formed in 1983, Bon Jovi consists of lead singer and namesake Jon Bon Jovi, pianist and keyboardist David Bryan, drummer Tico Torres, lead guitarist Phil X, and bassist Hugh McDonald.The band\'s lineup has remained mostly static during its history, with the only exceptions being the 1994 dismissal of bass player Alec John Such, who was unofficially replaced by Hugh McDonald, and the departure of longtime guitarist and co-songwriter Richie Sambora in 2013. Phil X and McDonald both became official members in 2016.');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Bruno Mars','2004-present','R&B, funk','Honolulu, Hawaii, U.S.','Universal Motown','Peter Gene Hernandez (born October 8, 1985), known professionally as Bruno Mars, is an American singer-songwriter, multi-instrumentalist, record producer, and choreographer. Born and raised in Honolulu, Hawaii, by a family of musicians, Mars began making music at a young age and performed in various musical venues in his hometown throughout his childhood. He graduated from high school and moved to Los Angeles to pursue a musical career. After being dropped by Motown Records, Mars signed a recording contract with Atlantic Records in 2009.');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Josh Groban','1997-present','Easy Listening','Los Angeles, California, U.S.','Reprise','Joshua Winslow Groban (born February 27, 1981) is an American singer, songwriter, actor, and record producer. His first four solo albums have been certified multi-platinum, and he was charted in 2007 as the number-one bestselling artist in the United States, with over 22.3 million records in the nation. As of 2012, he had sold over 25 million records worldwide.');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Justin Bieber','2007-present','Pop, R&B','London, Ontario, Canada','IslandTeen Island','Justin Drew Bieber is a Canadian Singer and songwriter. After a talent manager discovered him through his You Yoube vides covering songs in 2008 and singed to RBMG, Bieber release his debut EP, My World in late 2009. It was certified Platinum in the U.S. He became the first artist to have seven songs from a debt record chart on the Billboard Hot 100. ');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Katy Perry','2001-present','Pop.rock','Santa Barbara, California, U.S.','Red Hill. Java','Katheryn Elizabeth Hudson (born October 25, 1984), known professionally as Katy Perry, is an American singer and songwriter. After singing in church during her childhood, she pursued a career in gospel music as a teenager. Perry signed with Red Hill Records and released her debut studio album Katy Hudson under her birth name in 2001, which was commercially unsuccessful. She moved to Los Angeles the following year to venture into secular music after Red Hill ceased operations and she subsequently began working with producers Glen Ballard, Dr. Luke, and Max Martin. After adopting the stage name Katy Perry and being dropped by The Island Def Jam Music Group and Columbia Records, she signed a recording contract with Capitol Records in April 2007.');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Kelly Clarkson','2002-present','Soul','Burleson Texas','Atlantic','Kelly Brianne Clarkson (born April 24, 1982) is an American singer, songwriter, actress, and author. She rose to fame in 2002 after winning the inaugural season of the television series American Idol, which earned her a record deal with RCA Records. Clarkson\'s debut single, \"Before Your Love/A Moment Like This\", topped the US Billboard Hot 100 chart and became the best-selling single of 2002 in the nation. It was followed by the release of her debut studio album, Thankful (2003), which debuted at number one on the Billboard 200 chart. ');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Lady Gaga','2001-present','Pop, dance, electronic','Manhattan, New York, U.S.','Def Jam Cherry tree','Stefani Joanne Angelina Germanotta(born March 28, 1986), known professionally as Lady Gaga, is an American singer, songwriter, and actress. She is known for her unconventionality and provocative work as well as experimenting with new images.');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Mariah Carey','1988-present','R&B, Pop, Hip Hop','New York City','Columbia, Virgin','Mariah Carey (born March 27, 1969 or 1970) is an American singer, songwriter, record producer, and actress. After signing to Columbia Records, she released her debut album, Mariah Carey (1990), which spawned four number-one singles on the US Billboard Hot 100 chart; \"Vision of Love\", \"Love Takes Time\", \"Someday\", and \"I Don\'t Wanna Cry.\" Following her marriage to Sony Music head Tommy Mottola, Carey became the label\'s highest-selling act with the albums Music Box (1993), Merry Christmas (1994), and Daydream (1995). These albums spawned a string of successfu');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Megan Trainor','2009-present','R&B, pop','Nantucket, Massachusetts,U.S.','Epic','Meghan Elizabeth Trainor(born December 22, 1993) is an American singer and songwriter.Trainor\'s work has been recognized with several awards and nominations, including a Grammy Award, Music Business Association\'s Breakthrough Artist of the Year accolade and two Billboard Music Awards. Trainor was interested in music from a young age, and wrote, recorded, performed, and produced three independently-released albums between ages 15 and 17. In 2011, she signed a publishing deal with Big Yellow Dog Music, and pursued a career in songwriting. After signing a record deal with Epic Records in 2014, Trainor rose to fame with the release of her major-label debut studio album, Title (2015). The album debuted at number one on the US Billboard 200, went on to sell over one million copies domestically,and produced three top 10 singles: \"All About That Bass\", \"Lips Are Movin\" and \"Like I\'m Gonna Lose You\".');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Michael Buble','1996-present','Traditional pop','Burnaby, British Columbia','Reprise','Michael Steven Bublé is a Canadian singer, songwriter, actor and record producer. He was recognized as an Italian citizen since birth by jure sanguinis in 2005.[3]He has won several awards, including four Grammy Awards[4][5] and multiple Juno Awards.[6]');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Pink','1995-present','Pop','Philadelphia','LaFace','Alecia Beth Moore (born September 8, 1979), known professionally as Pink (stylized as P!nk), is an American singer, songwriter, dancer and actress. She was signed to her first record label with original R&B girl group Choice in 1995. The label, LaFace Records, only saw potential in Pink, offering her a solo deal. Choice disbanded in 1998. Pink rose as an artist with her debut solo album, Can\'t Take Me Home (2000). It was certified double-platinum in the United States and spawned two Billboard Hot 100 top-ten hits: \"There You Go\" and \"Most Girls\". She gained further recognition with the Moulin Rouge! Soundtrack \"Lady Marmalade\", which gave Pink her first Grammy Award as well as her first number-one single on the Billboard Hot 100. Pink took more artistic control and pursued a pop rock direction for her second album, Missundaztood (2001). ');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Taylor Swift','2004-present','Pop, country','Reading, Pennsylvania','RCA Big machine','Taylor Alison Swift (born December 13, 1989) is an American singer-songwriter. One of the leading contemporary recording artists, she is known for narrative songs about her personal life, which have received widespread media coverage.\nBorn and raised in Pennsylvania, Swift moved to Nashville, Tennessee at the age of 14 to pursue a career in country music. She signed with the label Big Machine Records and became the youngest artist ever signed by the Sony/ATV Music publishing house. Her self-titled debut album in 2006 peaked at number five on the Billboard 200 and spent the most weeks on the chart in the 2000s. The album\'s third single, \"Our Song\", made her the youngest person to single-handedly write and perform a number-one song on the Hot Country Songs chart. Swift\'s second album, Fearless, was released in 2008. Buoyed by the success of pop crossover singles \"Love Story\" and \"You Belong with Me\", Fearless became the best-selling album of 2009 in the United States. The album won four Grammy Awards, with Swift becoming the youngest Album of the Year winner.\n');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Woodkid','2006-present','Pop, Chamber Pop, Art Pop, Neofolk','Lyon, France','Green United Music','Yoann Lemoine (born 16 March 1983) is a French music video director, graphic designer and singer-songwriter. His most notable works include his music video direction for Katy Perry\'s Teenage Dream, Taylor Swift\'s single Back to December, Lana Del Rey\'s Born to Die and Mystery Jets\' Dreaming of Another World.Lemoine is also a neofolk musician, going by the stage name Woodkid. On March 28, 2011, Woodkid released his first EP Iron EP, and on March 18, 2013, he released his first album titled The Golden Age, which is an autobiographical record. In June 2010, he received 5 Lions for his AIDS Awareness campaign Graffiti at the Cannes Lions Advertising festival. In 2012, Lemoine received the award for Best Director of the Year at the MVPA Awards in Los Angeles and was nominated for 6 MTV Video Music awards for his videos for Lana Del Rey, Drake, and Rihanna.');
INSERT INTO `artists` (`artistName`,`artistDate`,`artistGenre`,`artistOrigin`,`artistLabels`,`bioText`) VALUES ('Yanni','1980-present','Contemporary, instrumental, world, crossover','Kalamata, Greece','Virgin,EMI','Yiannis Chryssomallis born November 14, 1954), known professionally as Yanni , is a Greek composer, keyboardist, pianist, and music producer who has spent his adult life in the United States.Yanni continues to use the musical shorthand that he developed as a child, blending jazz, classical, soft rock, and world music[4] to create predominantly instrumental works. Although this genre of music was not well suited for commercial pop radio and music television, Yanni received international recognition by producing concerts at historic monuments and by producing videos that were broadcast on public television. ');
